version: "3.8"
services:
  app:
    build: ./server
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - .:/app
  redis:
    ports:
      - "6379:6379"
    image: "redis:6.0.10-alpine"
  postgre-db:
    ports:
      - "5432:5432"
    image: "postgres:13.2-alpine"
    environment:
      POSTGRES_PASSWORD: authserver
      POSTGRES_USER: authserver
      POSTGRES_DB: authserver