version: "3.8"
services:
#  app:
#    build: ""
#    ports:
#      - "8080:8080"
#      - "5005:5005"
#    volumes:
#      - .:/app
  redis:
    ports:
      - "6379:6379"
    image: "redis:6.2-alpine"
    command: redis-server --requirepass authserver
  postgre-db:
    ports:
      - "5432:5432"
    image: "postgres:13.2-alpine"
    environment:
      POSTGRES_PASSWORD: authserver
      POSTGRES_USER: authserver
      POSTGRES_DB: authserver
  mongodb:
    image: "mongo"
    restart: always
    ports:
      - "47017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=authserver
      - MONGO_INITDB_ROOT_PASSWORD=authserver
      - MONGO_INITDB_DATABASE=authserver
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
