version: "3.9"
services:
  redis:
    ports:
      - "6379:6379"
    image: "redis:6.2-alpine"
    command: redis-server --requirepass authserver
  postgre-db:
    ports:
      - "25432:5432"
    image: "postgres:14.0-alpine"
    environment:
      POSTGRES_PASSWORD: authserver
      POSTGRES_USER: authserver
      POSTGRES_DB: authserver
    volumes:
      - /home/nagygm/docker_environments/authorization-server/postgres-db/postgresql:/var/lib/postgresql
      - /home/nagygm/docker_environments/authorization-server/postgres-db/data:/var/lib/postgresql/data
  mongodb:
    image: "mongo:5.0.3"
    restart: always
    ports:
      - "47017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=authserver
      - MONGO_INITDB_ROOT_PASSWORD=authserver
      - MONGO_INITDB_DATABASE=authserver
    volumes:
      - /mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - /home/nagygm/docker_environments/authorization-server/mongodb/data:/data/db
#  tc-server:
#    image: "jetbrains/teamcity-server:latest"
#    depends_on:
#      - "postgre-db"
#    ports:
#      - "8111:8111"
#    volumes:
#      - /home/nagygm/docker_environments/authorization-server/teamcity-server-data/datadir:/data/teamcity_server/datadir
#      - /home/nagygm/docker_environments/authorization-server/teamcity-server-data/logs:/opt/teamcity/logs
#  tc-agent:
#    image: "jetbrains/teamcity-agent"
#    depends_on:
#      - "tc-server"
#    environment:
#      - SERVER_URL=tc-server
#      - AGENT_NAME=local-docker
  jenkins:
    image: "jenkins/jenkins:lts-jdk11"
    ports:
      - "8080:8080"
      - "50000:50000"
